[project]
name = "shioaji-stock-project"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.30.1",
    "json5>=0.12.1",
    "nbstripout>=0.8.2",
    "numpy>=2.3.2",
    "pandas>=2.3.2",
    "python-dotenv>=1.1.1",
    "rich>=14.1.0",
    "shioaji[speed]>=1.2.7",
]
